DLQ Listeners with Resubmitting Publishers
harvard-lts/hdc3a-dlq-handler-service pull request #2
Opened 2022-05-20 07:25 UTC by GPortas

**DLQ Listeners with Resubmitting Publishers**
* * *
Note: [PR #1](https://github.com/harvard-lts/hdc3a-dlq-handler-service/pull/1) should be reviewed and merged first.

**GitHub Issue**: ([link](https://app.zenhub.com/workspaces/hdc-62163f60fb08c60011fa4795/issues/harvard-lts/hdc/184))

* Other Relevant Links: [PR #1](https://github.com/harvard-lts/hdc3a-dlq-handler-service/pull/1)

# What does this Pull Request do?
Adds DLQ Listeners for process and transfer MQs with resubmit logics through new Resubmitting Publishers.

# How should this be tested?

A description of what steps someone could take to:

* Make sure test .env variables are updated based on .env.example file
* Rebuild test environment: docker-compose -f docker-compose-test.yml build --no-cache
* Run the local test environment: `docker-compose -f docker-compose-test.yml up`
* Execute tests: `docker exec -it test_runner pytest test`

For a functional test:

* Make sure .env variables are updated based on .env.example file
* Run the local dev environment: `docker-compose -f docker-compose-dev.yml up`
* Create a queue called "test_queue" on any of the available MQs (Transfer or Process) using the ActiveMQ web console. 
* Send a test message to the queue with the following body:
`{"admin_metadata":{"original_queue":"test_queue","retry_count":0},"test":"test"}`
You can use the ActiveMQ web console to send the message:
![activemq_send_message](https://user-images.githubusercontent.com/17010447/169472880-6574974f-6c37-435d-8522-0502682d1a0a.png)
It is important to set a value in "Time to live" so that the message expires after that time and is sent to the DLQ.
* Check that the message has been resubmitted:
Since the message sent to test_queue is not being consumed, the message will always expire even if we resubmit the message several times.

The number of times the message is resubmitted to the queue must correspond to the maximum retries set in .env.

Once the test message has been sent and having waited for it to expire for each retry, for a maximum of 3 retries, the status of the queues should look like this:
![activemq_queues_status](https://user-images.githubusercontent.com/17010447/169474272-b65bb77c-349c-42d3-80c8-2ee1bd7c56d7.png)

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests Yes
- integration tests Yes

# Interested parties
@jessjass @ives1227 @adaybujeda 

Keyword: resolved

2022-05-20 10:48 UTC, adaybujeda commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +    def _handle_received_message(self, message_body: dict) -> None:
Should this logic be in a service class instead of the listener?

2022-05-20 10:50 UTC, adaybujeda commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +
Should invalid messages, the ones without admin_metadata or the original_queue be discarded automatically?

Wouldn't this hide errors as messages will disappear from the DLQ?

Should these messages be examined manually and discarded by an ops person?

2022-05-20 10:51 UTC, adaybujeda commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +
Id admin_metadata is there, should be default a retry count to a value?

2022-05-20 10:52 UTC, adaybujeda commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +        self._logger.info("Max retries permitted: {}".format(mq_max_retries))
it would be easier to track the log entries if the message_id, or other identifier is added to the log

2022-05-20 11:44 UTC, GPortas commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +    def _handle_received_message(self, message_body: dict) -> None:
Yes, It should. Will do. 👍

2022-05-20 15:42 UTC, ives1227 commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +
@GPortas this is a good point.  If you use client-individual for acknowledgement, you can manually send the ack once everything has been validated.  If it fails, it can be left and an email sent to the admins.

2022-05-20 15:52 UTC, ives1227 requested changes
Everything looks great.  The one change that would probably be necessary is to set the ack to client-individual so you don't dequeue messages that can't be requeued.  I added a comment inline for that.

2022-05-20 15:52 UTC, ives1227 commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +            return
See my response that is added to Aday's response.

2022-05-23 09:30 UTC, GPortas commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +    def _handle_received_message(self, message_body: dict) -> None:
Done! @adaybujeda

2022-05-24 09:31 UTC, GPortas commented on app/dlq/infrastructure/mq/listeners/dlq_queue_listener_base.py
> +
Thank you very much for your very valuable suggestions. I have implemented it that way.

Emailing to administrators will be implemented in HDC-217.

2022-05-25 17:09 UTC, ives1227 approved these changes
Everything looks good. DLQ is holding onto the invalid messages now.  Great!

2022-05-25 17:10 UTC, merged